Repository Learnathon-By-Geeky-Solutions/segfault, pull requests merged in 2025-01, with the labels that each got.

#1 Testing github setup with README Modification
  README.md
Labels: documentation

#9 Directory renaming
  backend/codesirius/codesirius/__init__.py
  backend/codesirius/codesirius/asgi.py
  backend/codesirius/codesirius/settings.py
  backend/codesirius/codesirius/urls.py
  backend/codesirius/codesirius/wsgi.py
  backend/codesirius/manage.py
  frontend/.gitkeep
Labels: enhancement

#14 New App Authentication Developed
  .gitignore
  backend/codesirius/authentication/__init__.py
  backend/codesirius/authentication/admin.py
  backend/codesirius/authentication/apps.py
  backend/codesirius/authentication/migrations/0001_initial.py
  backend/codesirius/authentication/migrations/0002_customuser_full_name.py
  backend/codesirius/authentication/migrations/__init__.py
  backend/codesirius/authentication/models.py
  backend/codesirius/authentication/serializers.py
  backend/codesirius/authentication/tests.py
  backend/codesirius/authentication/urls.py
  backend/codesirius/authentication/views.py
  backend/codesirius/codesirius/settings.py
  backend/codesirius/codesirius/urls.py
  backend/codesirius/db.sqlite3
  requirements.txt
Labels: enhancement, Backend

#17 Updated django version to resolve dependabot alert
  requirements.txt
Labels: enhancement, Backend, Security

#18 Potential denial-of-service vulnerability fix
  requirements.txt
Labels: enhancement, Backend, Security

#19 Feature/takrim/project code scoring locally
  SECURITY.md
  requirements.txt
  testscore.py
Labels: enhancement, Scoring

#20 Created a script that will asses our code locally
  requirements.txt
  testscore.py
Labels: enhancement, Scoring

#32 Added support for Postgresql
  backend/Dockerfile
  backend/codesirius/codesirius/settings.py
  backend/requirements.txt
  docker-compose.yml
Labels: Backend

#34 Allowed all common development hosts
  backend/codesirius/codesirius/settings.py
Labels: enhancement, Backend
